MyTLearn/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from MyTLearn import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('my/', personal, name='personal'),
    path('my/users', users_list, name='users'),
    path('logout/', logout_user, name='logout'),
    path('my/users/create', create_user, name='userCreate'),
    path('my/groups', groups_list, name='groups'),
    path('my/groups/create', create_group, name='groupCreate'),
    path('my/group/<int:pk>', group_detail, name='groupDetail'),
    path('my/group/blocked', group_no_perm, name='noPermForGroup'),
    path('my/studentgroups', student_groups, name='studentGroups'),
    path('my/tutorgroups', tutor_groups, name='tutorGroups'),
    path('my/studentmarks', students_marks, name='studentMarks')
]

core/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.urls import reverse

from accounts.models import User


# Create your models here.
class WorkDay(models.Model):
    DAY = (
        ('ПН', 'Понедельник'),
        ('ВТ', 'Вторник'),
        ('СР', 'Среда'),
        ('ЧТ', 'Четверг'),
        ('ПТ', 'Пятница'),
        ('СБ', 'Суббота'),
        ('ВС', 'Воскресенье'),
    )
    day = models.CharField(max_length=10, choices=DAY)

    def __str__(self):
        return self.day


class Department(models.Model):
    depTitle = models.CharField(max_length=150, unique=True)
    groupPrice = models.IntegerField()
    indPrice = models.IntegerField()

    def __str__(self):
        return self.depTitle


class WorkGroupPost(models.Model):
    class Meta:
        ordering = ['-postCreationDate']

    TYPE = (
        ('Сообщение', 'Сообщение'),
        ('Важно', 'Важно'),
        ('Домашнее задание', 'Домашнее задание')
    )

    postTag = models.CharField(max_length=100, choices=TYPE)
    postTitle = models.CharField(max_length=200)
    postBody = models.TextField()
    postCreationDate = models.DateTimeField(auto_now_add=True)


class GroupHomeTask(models.Model):
    class Meta:
        ordering = ['-taskDate']

    taskTitle = models.CharField(max_length=100)
    taskDescription = models.TextField()
    taskDate = models.DateTimeField(auto_now_add=True)
    taskDeadline = models.DateTimeField()
    taskFile = models.FileField(upload_to='hometaskfiles/', blank=True, null=True)
    taskSolutions = models.ManyToManyField('GroupTaskSolution', blank=True, null=True)

    def add_to_group(self, group):
        group.groupHometasks.add(self)

    def __str__(self):
        return self.taskTitle


class GroupTaskSolution(models.Model):
    solutionFrom = models.ForeignKey('accounts.User', related_name='solution_from', on_delete=models.CASCADE)
    solutionFile = models.FileField(upload_to='tasksolutions/')
    solutionForTask = models.ForeignKey('GroupHomeTask', related_name='solution_for_task', on_delete=models.CASCADE)
    solutionDatetime = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def add_to_task(self):
        print(self.solutionForTask)
        self.solutionForTask.taskSolutions.add(self)


class Mark(models.Model):
    markForUser = models.ForeignKey("accounts.User", on_delete=models.CASCADE)
    markValue = models.IntegerField(default=0, validators=[
        MaxValueValidator(100),
        MinValueValidator(0)
    ])
    markTarget = models.CharField(max_length=500)
    markGroup = models.ForeignKey('WorkGroup', on_delete=models.CASCADE)
    markComment = models.CharField(max_length=1000)
    markConnectedTask = models.ForeignKey('GroupHomeTask', on_delete=models.CASCADE, blank=True)


class WorkGroup(models.Model):
    TYPE = (
        ('Групповые занятия', 'Групповые занятия'),
        ('Индивидуальные занятия', 'Индивидуальные занятия')
    )
    groupName = models.CharField(max_length=100, unique=True)
    groupType = models.CharField(max_length=100, choices=TYPE, default=TYPE[0])
    groupDep = models.ForeignKey(Department, on_delete=models.CASCADE, blank=True, null=True)
    groupTeacher = models.ForeignKey('accounts.User', on_delete=models.CASCADE)
    groupDays = models.ManyToManyField(WorkDay, related_name='group_days')
    groupStudents = models.ManyToManyField(User, related_name='group_students', blank=True)
    groupTime = models.CharField(max_length=1000, default='', blank=True)
    groupPosts = models.ManyToManyField(WorkGroupPost, related_name='group_posts')
    groupHometasks = models.ManyToManyField(GroupHomeTask, related_name='groups_tasks')

    def get_absolute_url(self):
        return reverse('groupDetail', kwargs={'pk': self.pk})

    def add_student(self, student: User):
        if student.is_student():
            self.groupStudents.add(student)
            student.work_groups.add(self)

    def __str__(self):
        return self.groupName

templates/pages/general/group_detail.html
{% extends 'personal.html' %}
{% load crispy_forms_filters %}
{% load static %}
{% load core_tags %}

{% block title %}
    Группа {{ group.groupName }}
{% endblock %}

{% block section %}
    <style>
        .info-menu-item {
            margin: 10px;
            font-weight: bold;
            color: #848582;
            cursor: pointer;

            transition: 0.2s;
        }

        .info-menu-item:hover {
            color: #474846;
        }

        .group-info-section {
            display: none;
        }

        .group-info-section.show {
            display: block;
        }
    </style>
    <div class="white-section">
        <h2>{{ group.groupName }}</h2>
    </div>
    <div class="d-sm-flex justify-content-around" style="padding: 0px !important;">
        <div class="d-sm-flex flex-column p-0 m-0">
            <div class="white-section">
                <h3>Расписание</h3>
                <p>{% schedule group %}</p>
            </div>
            <div class="white-section">
                <h3>Студенты</h3>
                {% if request.user.is_admin %}
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addUserModal">
                        Добавить
                    </button>
                {% endif %}
                {% for s in group.groupStudents.all %}
                    <p>{{ s }}</p>
                {% endfor %}
            </div>
        </div>
        <div class="d-sm-flex flex-column p-0 m-0 w-100">
            <div class="white-section">
                <div class="d-sm-flex align-items-center mb-4">
                    <div class="info-menu-item" activate-section="group-posts">Уведомления</div>
                    <div class="info-menu-item" activate-section="group-home-tasks">Домашние задания</div>
                </div>
                <div class="group-info-section show" id="group-posts">
                    <h4>Уведомления</h4>
                    {% if request.user.is_admin or request.user.is_tutor %}
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal"
                                data-bs-target="#createPostModal">
                            + Добавить
                        </button>
                    {% endif %}
                    {% for post in group.groupPosts.all %}
                        {% postdecor post %}
                    {% endfor %}
                </div>
                <div class="group-info-section" id="group-home-tasks">
                    <h4>Домашние задания</h4>
                    {% if request.user.is_tutor or request.user.is_admin %}
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal"
                                data-bs-target="#createTaskModal">
                            + Добавить
                        </button>
                    {% endif %}
                    {% for task in group.groupHometasks.all %}
                        {% taskdecor task %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    {% if request.user.is_admin %}
        <div class="modal fade" id="addUserModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
             aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="staticBackdropLabel">Добавление ученика в группу</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form method="POST">
                            {% csrf_token %}
                            {{ addUserForm|crispy }}
                            <button type="submit" class="btn btn-primary">Добавить</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

    {% if request.user.is_tutor or request.user.is_admin %}
        <div class="modal fade" id="createTaskModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
             aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="staticBackdropLabel">Новое домашнее задание</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ createTaskForm|crispy }}
                            <button type="submit" class="btn btn-primary">Добавить</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="createPostModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
             aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="staticBackdropLabel">Новое уведомление</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form method="POST">
                            {% csrf_token %}
                            {{ createPostForm|crispy }}
                            <button type="submit" class="btn btn-primary">Создать</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

    {% if request.user.is_student %}
        <div class="modal fade" id="sendSolutionModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
             aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="sendSolutionTitle">Отправка решения</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ sendTaskSolutionForm|crispy }}
                            <button type="submit" class="btn btn-primary">Отправить</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

    <script src="{% static 'js/GroupInfoSectionsController.js' %}"></script>
    <script>
        function ShowSendSolutionModal(src) {
            const sendTaskSolutionModal = new bootstrap.Modal('#sendSolutionModal', {});
            document.querySelector('#id_solutionFrom').value = {{ request.user.pk }};
            document.querySelector('#id_solutionForTask').value = src.getAttribute('tid');
            sendTaskSolutionModal.show();
        }
    </script>
{% endblock %}

templates/pages/general/no_perm_to_group.html
{% extends 'base.html' %}

{% block title %}
    У вас нет прав просмотра
{% endblock %}

{% block content %}
    <div style="height: 100vh;">
        <div class="h-100 d-sm-flex align-items-center justify-content-around">
            <div class="white-section">
                <h1>У вас нет прав на просмотр</h1>
                <p>Вы не состоите в этой группе</p>
            </div>
        </div>
    </div>
{% endblock %}